// <auto-generated />
using System;
using System.Collections.Generic;
using LoanManagement.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LoanManagement.Domain.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250922165102_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundElectionEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<long>("CandidateID")
                        .HasColumnType("serial");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("ElectionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FundID")
                        .HasColumnType("serial");

                    b.Property<string>("FundStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Votes")
                        .HasColumnType("integer");

                    b.HasKey("RowId");

                    b.HasIndex("CandidateID");

                    b.HasIndex("FundID");

                    b.ToTable("FundElection", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FundType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.ToTable("Fund", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundExecutiveEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("Elected")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FundID")
                        .HasColumnType("serial");

                    b.Property<bool>("HasSignPermission")
                        .HasColumnType("boolean");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("PersonnelID")
                        .HasColumnType("serial");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.HasIndex("PersonnelID");

                    b.ToTable("FundExecutive", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundHierarchyEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long?>("FundID")
                        .HasColumnType("serial");

                    b.Property<long?>("ParentFundID")
                        .HasColumnType("serial");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.HasIndex("ParentFundID");

                    b.ToTable("FundHierarchy", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundInspectorEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FundID")
                        .HasColumnType("serial");

                    b.Property<long>("PersonnelID")
                        .HasColumnType("serial");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ReportFrequency")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.HasIndex("PersonnelID");

                    b.ToTable("FundInspector", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundInsuranceEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("FundID")
                        .HasColumnType("serial");

                    b.Property<decimal>("InsuranceAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("InsuranceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LoanRequestID")
                        .HasColumnType("serial");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.HasIndex("LoanRequestID");

                    b.ToTable("FundInsurance", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundMemberEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("FundID")
                        .HasColumnType("serial");

                    b.Property<string>("MembershipNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("MembershipType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("NetPayment")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long?>("PersonnelID")
                        .HasColumnType("serial");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.PrimitiveCollection<List<string>>("ShareDeductionCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal>("Shares")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("TotalSalary")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WaitingMonths")
                        .HasColumnType("integer");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.HasIndex("PersonnelID");

                    b.ToTable("FundMember", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundRegionEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<int>("ActiveMembers")
                        .HasColumnType("integer");

                    b.Property<string>("BankName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("BranchCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("FundID")
                        .HasColumnType("serial");

                    b.PrimitiveCollection<List<string>>("InstallmentDeductionCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("OrgCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("RegionName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("RetiredMembers")
                        .HasColumnType("integer");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.PrimitiveCollection<List<string>>("ShareDeductionCodes")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.ToTable("FundRegion", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundReportEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<bool>("Approved")
                        .HasColumnType("boolean");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("FundID")
                        .HasColumnType("serial");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ReportType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("ReportYear")
                        .HasColumnType("integer");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.ToTable("FundReport", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundSettingEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<decimal>("CommissionPercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("FundID")
                        .HasColumnType("serial");

                    b.Property<decimal>("InsurancePercent")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("LoanMultiplier")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("MaxInstallmentChange")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<decimal>("MaxLoanAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MinMembershipMonths")
                        .HasColumnType("integer");

                    b.Property<decimal>("MinShareAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("MultiPaymentAllowed")
                        .HasColumnType("boolean");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<int>("RepaymentMonths")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(36);

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<bool>("SingleLoanPerMember")
                        .HasColumnType("boolean");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.ToTable("FundSetting", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundTransactionEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Commission")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("FundID")
                        .HasColumnType("serial");

                    b.Property<decimal>("Insurance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("MemberID")
                        .HasColumnType("serial");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.HasIndex("MemberID");

                    b.ToTable("FundTransaction", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundTransferEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<long>("FromFundID")
                        .HasColumnType("serial");

                    b.Property<long>("MemberID")
                        .HasColumnType("serial");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("ToFundID")
                        .HasColumnType("serial");

                    b.Property<DateTime?>("TransferDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransferType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("FromFundID");

                    b.HasIndex("MemberID");

                    b.HasIndex("ToFundID");

                    b.ToTable("FundTransfer", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanAdjustmentRequestEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<decimal>("MaxAllowed")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<long>("MemberID")
                        .HasColumnType("serial");

                    b.Property<decimal>("NewValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OldValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<DateTime>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("MemberID");

                    b.ToTable("LoanAdjustmentRequest", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanCertificateEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<string>("CertificateNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("IssueDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LoanRequestID")
                        .HasColumnType("serial");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("LoanRequestID");

                    b.ToTable("LoanCertificate", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanGuarantorEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("GuaranteeDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuarantorCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("LoanGuarantorStatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("LoanRequestID")
                        .HasColumnType("serial");

                    b.Property<long>("PersonnelID")
                        .HasColumnType("serial");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("LoanRequestID");

                    b.HasIndex("PersonnelID");

                    b.ToTable("LoanGuarantor", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanRepaymentEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<long>("LoanRequestID")
                        .HasColumnType("serial");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentGatewayRef")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("ReceiptNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("LoanRequestID");

                    b.ToTable("LoanRepayment", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanRequestEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("AmountRequested")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("BankAccount")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmploymentType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("FundID")
                        .HasColumnType("serial");

                    b.Property<int>("Installments")
                        .HasColumnType("integer");

                    b.Property<long>("LoanTypeID")
                        .HasColumnType("serial");

                    b.Property<decimal>("MaxLoanAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Mobile")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal>("MonthlyInstallment")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("Online")
                        .HasColumnType("boolean");

                    b.Property<long>("PersonnelID")
                        .HasColumnType("serial");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("RequiresGuarantor")
                        .HasColumnType("boolean");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("StatusDesc")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WaitingMonths")
                        .HasColumnType("integer");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.HasIndex("LoanTypeID");

                    b.HasIndex("PersonnelID");

                    b.ToTable("LoanRequest", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanRequestLogEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ActionBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("ActionDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("LoanRequestID")
                        .HasColumnType("serial");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("LoanRequestID");

                    b.ToTable("LoanRequestLog", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanTypeEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("FundID")
                        .HasColumnType("serial");

                    b.Property<decimal>("MaxAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MaxInstallments")
                        .HasColumnType("integer");

                    b.Property<int>("MinInstallments")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("FundID");

                    b.ToTable("LoanType", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.NotificationEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("NotificationDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<short?>("NotificationStatus")
                        .HasColumnType("smallint");

                    b.Property<string>("NotificationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("PersonnelID")
                        .HasColumnType("serial");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<bool>("Read")
                        .HasColumnType("boolean");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.HasIndex("PersonnelID");

                    b.ToTable("Notification", "LON");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.PersonnelEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("serial")
                        .HasColumnName("row_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<long>("RowId"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Department")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("EmploymentCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("EmploymentType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("FatherName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Mobile")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Province")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.Property<short>("RevSeq")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1);

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("RowId");

                    b.ToTable("Personnel", "Entity");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundElectionEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.PersonnelEntity", "Candidate")
                        .WithMany()
                        .HasForeignKey("CandidateID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Candidate");

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundExecutiveEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.PersonnelEntity", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundHierarchyEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "ParentFund")
                        .WithMany()
                        .HasForeignKey("ParentFundID");

                    b.Navigation("Fund");

                    b.Navigation("ParentFund");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundInspectorEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.PersonnelEntity", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundInsuranceEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.LoanRequestEntity", "LoanRequest")
                        .WithMany()
                        .HasForeignKey("LoanRequestID");

                    b.Navigation("Fund");

                    b.Navigation("LoanRequest");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundMemberEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.PersonnelEntity", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundRegionEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundReportEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundSettingEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundTransactionEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.FundMemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.FundTransferEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "FromFund")
                        .WithMany()
                        .HasForeignKey("FromFundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.FundMemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "ToFund")
                        .WithMany()
                        .HasForeignKey("ToFundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FromFund");

                    b.Navigation("Member");

                    b.Navigation("ToFund");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanAdjustmentRequestEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundMemberEntity", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Member");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanCertificateEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.LoanRequestEntity", "LoanRequest")
                        .WithMany()
                        .HasForeignKey("LoanRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanRequest");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanGuarantorEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.LoanRequestEntity", "LoanRequest")
                        .WithMany()
                        .HasForeignKey("LoanRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.PersonnelEntity", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanRequest");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanRepaymentEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.LoanRequestEntity", "LoanRequest")
                        .WithMany()
                        .HasForeignKey("LoanRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanRequest");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanRequestEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.LoanTypeEntity", "LoanType")
                        .WithMany()
                        .HasForeignKey("LoanTypeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LoanManagement.Domain.Entities.PersonnelEntity", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");

                    b.Navigation("LoanType");

                    b.Navigation("Personnel");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanRequestLogEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.LoanRequestEntity", "LoanRequest")
                        .WithMany()
                        .HasForeignKey("LoanRequestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoanRequest");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.LoanTypeEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.FundEntity", "Fund")
                        .WithMany()
                        .HasForeignKey("FundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Fund");
                });

            modelBuilder.Entity("LoanManagement.Domain.Entities.NotificationEntity", b =>
                {
                    b.HasOne("LoanManagement.Domain.Entities.PersonnelEntity", "Personnel")
                        .WithMany()
                        .HasForeignKey("PersonnelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Personnel");
                });
#pragma warning restore 612, 618
        }
    }
}
