<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="13.0.0" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.9" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Aspire\Raya.CommonMicroServices.ServiceDefaults\Raya.CommonMicroServices.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\..\Shared\raya.hrm.shared.library\Raya.Hrm.Shared.Library.csproj" />
    <ProjectReference Include="..\Log.Service\Log.Service.csproj" />
  </ItemGroup>

</Project>
