// <auto-generated />
using System;
using Example.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Example.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251013134148_Ah03")]
    partial class Ah03
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Example.Domain.Entities.ActivityFormEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<DateOnly>("ActivityDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RevSeq")
                        .HasColumnType("smallint");

                    b.Property<long>("SelectedProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("SelectedStudentId")
                        .HasColumnType("bigint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RowId");

                    b.HasIndex("SelectedProgramId");

                    b.HasIndex("SelectedStudentId");

                    b.ToTable("ActivityForms");
                });

            modelBuilder.Entity("Example.Domain.Entities.DurationDateEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("EndDur")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RevSeq")
                        .HasColumnType("smallint");

                    b.Property<DateOnly>("StartDur")
                        .HasColumnType("date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RowId");

                    b.ToTable("DurationDateEntitys");
                });

            modelBuilder.Entity("Example.Domain.Entities.ImagesEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhotoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RevSeq")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RowId");

                    b.HasIndex("StudentId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Example.Domain.Entities.PhoneNumberEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ownership")
                        .HasColumnType("int");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RevSeq")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<long>("StudentId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RowId");

                    b.HasIndex("StudentId");

                    b.ToTable("PhoneNumbers");
                });

            modelBuilder.Entity("Example.Domain.Entities.ProgramEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("From")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RevSeq")
                        .HasColumnType("smallint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime?>("To")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RowId");

                    b.ToTable("Programs");
                });

            modelBuilder.Entity("Example.Domain.Entities.ScoreFormEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<long>("ActivityDurId")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RevSeq")
                        .HasColumnType("smallint");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<long>("SelectedProgramId")
                        .HasColumnType("bigint");

                    b.Property<long>("SelectedStudentId")
                        .HasColumnType("bigint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RowId");

                    b.HasIndex("ActivityDurId");

                    b.HasIndex("SelectedProgramId");

                    b.HasIndex("SelectedStudentId");

                    b.ToTable("ScoreForms");
                });

            modelBuilder.Entity("Example.Domain.Entities.SediqEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RevSeq")
                        .HasColumnType("smallint");

                    b.Property<string>("sediqName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("SediqCode")
                        .HasColumnType("bigint");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("RowId");

                    b.ToTable("sediqs");
                });

            modelBuilder.Entity("Example.Domain.Entities.StudentEntity", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EducationStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherJob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FatherName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldOfStudy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("MembershipDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RandId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("RevSeq")
                        .HasColumnType("smallint");

                    b.Property<long>("sediqRowId")
                        .HasColumnType("bigint");

                    b.Property<long>("SediqCode")
                        .HasColumnType("bigint");

                    b.Property<short>("Status")
                        .HasColumnType("smallint");

                    b.Property<string>("StudentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("YearStudy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId");

                    b.HasIndex("sediqRowId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Raya.Hrm.Shared.Library.Models.Auth.Authentication", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("RowId")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Description");

                    b.Property<string>("OwnerProject")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("OwnerProject");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<long?>("UserType")
                        .HasColumnType("bigint")
                        .HasColumnName("UserType");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Username");

                    b.HasKey("RowId");

                    b.ToTable("authentication", "auth");

                    b.HasData(
                        new
                        {
                            RowId = 1L,
                            Description = "1",
                            OwnerProject = "AllProjectOwner",
                            Password = "bJKg0LB4QfRPW8dIbQqLyg==",
                            UserType = 1L,
                            Username = "ADMIN"
                        });
                });

            modelBuilder.Entity("Raya.Hrm.Shared.Library.Models.Auth.Permission", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<string>("ActionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ControllerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("RoleRowId")
                        .HasColumnType("bigint");

                    b.HasKey("RowId");

                    b.HasIndex("RoleRowId");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("Raya.Hrm.Shared.Library.Models.Auth.PermissionRole", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("PermissionID")
                        .HasColumnType("bigint");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("RowId");

                    b.ToTable("PermissionRole");
                });

            modelBuilder.Entity("Raya.Hrm.Shared.Library.Models.Auth.Role", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<long?>("AuthenticationRowId")
                        .HasColumnType("bigint");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RowId");

                    b.HasIndex("AuthenticationRowId");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("Raya.Hrm.Shared.Library.Models.Auth.UserRole", b =>
                {
                    b.Property<long>("RowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityAlwaysColumn);

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("RowId"));

                    b.Property<long>("AuthenticationOrMemberID")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("RoleID")
                        .HasColumnType("bigint");

                    b.HasKey("RowId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("Example.Domain.Entities.ActivityFormEntity", b =>
                {
                    b.HasOne("Example.Domain.Entities.ProgramEntity", "SelectedProgram")
                        .WithMany("activityForms")
                        .HasForeignKey("SelectedProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Example.Domain.Entities.StudentEntity", "Student")
                        .WithMany("ActivityForms")
                        .HasForeignKey("SelectedStudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SelectedProgram");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Example.Domain.Entities.ImagesEntity", b =>
                {
                    b.HasOne("Example.Domain.Entities.StudentEntity", "Student")
                        .WithMany("Photos")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Example.Domain.Entities.PhoneNumberEntity", b =>
                {
                    b.HasOne("Example.Domain.Entities.StudentEntity", "Student")
                        .WithMany("PhoneNumbers")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Example.Domain.Entities.ScoreFormEntity", b =>
                {
                    b.HasOne("Example.Domain.Entities.DurationDateEntity", "ActivityDur")
                        .WithMany("ScoreForm")
                        .HasForeignKey("ActivityDurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Example.Domain.Entities.ProgramEntity", "SelectedProgram")
                        .WithMany("ScoreForms")
                        .HasForeignKey("SelectedProgramId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Example.Domain.Entities.StudentEntity", "SelectedStudent")
                        .WithMany("ScoreForms")
                        .HasForeignKey("SelectedStudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ActivityDur");

                    b.Navigation("SelectedProgram");

                    b.Navigation("SelectedStudent");
                });

            modelBuilder.Entity("Example.Domain.Entities.StudentEntity", b =>
                {
                    b.HasOne("Example.Domain.Entities.SediqEntity", "sediq")
                        .WithMany("Students")
                        .HasForeignKey("sediqRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("sediq");
                });

            modelBuilder.Entity("Raya.Hrm.Shared.Library.Models.Auth.Permission", b =>
                {
                    b.HasOne("Raya.Hrm.Shared.Library.Models.Auth.Role", null)
                        .WithMany("Permissions")
                        .HasForeignKey("RoleRowId");
                });

            modelBuilder.Entity("Raya.Hrm.Shared.Library.Models.Auth.Role", b =>
                {
                    b.HasOne("Raya.Hrm.Shared.Library.Models.Auth.Authentication", null)
                        .WithMany("Roles")
                        .HasForeignKey("AuthenticationRowId");
                });

            modelBuilder.Entity("Example.Domain.Entities.DurationDateEntity", b =>
                {
                    b.Navigation("ScoreForm");
                });

            modelBuilder.Entity("Example.Domain.Entities.ProgramEntity", b =>
                {
                    b.Navigation("ScoreForms");

                    b.Navigation("activityForms");
                });

            modelBuilder.Entity("Example.Domain.Entities.SediqEntity", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Example.Domain.Entities.StudentEntity", b =>
                {
                    b.Navigation("ActivityForms");

                    b.Navigation("PhoneNumbers");

                    b.Navigation("Photos");

                    b.Navigation("ScoreForms");
                });

            modelBuilder.Entity("Raya.Hrm.Shared.Library.Models.Auth.Authentication", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Raya.Hrm.Shared.Library.Models.Auth.Role", b =>
                {
                    b.Navigation("Permissions");
                });
#pragma warning restore 612, 618
        }
    }
}
