<Project Sdk="Microsoft.NET.Sdk">

  <Sdk Name="Aspire.AppHost.Sdk" Version="9.0.0" />

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>b96e8e9a-4314-4166-8e33-e947cff78af5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.AppHost" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\MicroService\Example\Example.Web.Api\Example.Web.Api.csproj" />
    <ProjectReference Include="..\..\MicroService\LoanManagement\LoanManagement.WebApi\LoanManagement.WebApi\LoanManagement.WebApi.csproj" />
  </ItemGroup>

</Project>
